
version: 2
jobs:
  build:
  docker:
       - image: circleci/node:8.10
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:  - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}     
      - run:
          name: install-dependencies
          command: npm install
         

     
      - run:
          name: angular-build
          command: ng build 

        
      - run:
          name: angular-test
          command: ng test
        
      - run:
          name: angular-lint
          command: ng lint
        
    